'use client';

import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { fetchApi } from '@/lib/api/client';
import { getAccessToken } from '@/lib/auth';

interface EventItem { _id: string; title: string; date: string; startTime?: string; endTime?: string; location?: string; description?: string }

export default function EventsPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const token = getAccessToken();
  const [events, setEvents] = useState<EventItem[]>([]); const [form, setForm] = useState({ title: '', date: '', startTime: '', endTime: '', location: '', description: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);

  async function load() { const response = await fetchApi<EventItem[]>(`/invitations/${id}/events`, { token: token ?? undefined }); if (response.success) setEvents(response.data); else setError(response.error.message); }
  useEffect(() => { if (!token) router.replace('/auth/login'); else load(); }, [id]);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function addEvent(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(''); const response = await fetchApi<EventItem>(`/invitations/${id}/events`, { method: 'POST', token: token ?? undefined, body: JSON.stringify(form) }); setSaving(false); if (!response.success) return setError(response.error.message); setEvents((current) => [...current, response.data].sort((a, b) => a.date.localeCompare(b.date))); setForm({ title: '', date: '', startTime: '', endTime: '', location: '', description: '' }); }
  async function removeEvent(eventId: string) { if (!window.confirm('Delete this event?')) return; const response = await fetchApi(`/invitations/${id}/events/${eventId}`, { method: 'DELETE', token: token ?? undefined }); if (!response.success) return setError(response.error.message); setEvents((current) => current.filter((item) => item._id !== eventId)); }

  return <main className="min-h-screen bg-neutral-950 px-4 py-8 text-white"><div className="mx-auto max-w-6xl"><Link href={`/dashboard/invitations/${id}`} className="text-sm text-amber-300">← Invitation</Link><div className="mt-8"><h1 className="text-4xl font-serif font-bold">Events</h1><p className="mt-2 text-neutral-400">Add the ceremonies, parties, and moments in your invitation.</p></div>{error && <p className="mt-5 rounded-lg bg-rose-950/40 p-3 text-sm text-rose-300">{error}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-[1fr_380px]"><section className="space-y-4">{events.length === 0 ? <div className="rounded-2xl border border-dashed border-neutral-700 p-12 text-center text-neutral-500">No events yet.</div> : events.map((item) => <article key={item._id} className="rounded-2xl border border-neutral-800 bg-neutral-900/70 p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-serif text-2xl font-bold">{item.title}</h2><p className="mt-2 text-sm text-amber-300">{new Date(item.date).toLocaleDateString(undefined, { dateStyle: 'long' })}{item.startTime ? ` · ${item.startTime}` : ''}{item.endTime ? `–${item.endTime}` : ''}</p>{item.location && <p className="mt-1 text-sm text-neutral-400">{item.location}</p>}{item.description && <p className="mt-3 text-sm text-neutral-400">{item.description}</p>}</div><button onClick={() => removeEvent(item._id)} className="text-xs text-rose-400">Delete</button></div></article>)}</section><form onSubmit={addEvent} className="h-fit rounded-2xl border border-neutral-800 bg-neutral-900/70 p-5"><h2 className="font-serif text-2xl font-bold">Add event</h2><div className="mt-4 space-y-3"><Field label="Event name" value={form.title} onChange={(value) => update('title', value)} required /><Field label="Date" type="date" value={form.date} onChange={(value) => update('date', value)} required /><div className="grid grid-cols-2 gap-3"><Field label="Start" type="time" value={form.startTime} onChange={(value) => update('startTime', value)} /><Field label="End" type="time" value={form.endTime} onChange={(value) => update('endTime', value)} /></div><Field label="Location" value={form.location} onChange={(value) => update('location', value)} /><label className="block text-sm text-neutral-300">Description<textarea rows={3} value={form.description} onChange={(event) => update('description', event.target.value)} className="mt-2 w-full rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2.5 text-white" /></label><button disabled={saving} className="w-full rounded-lg bg-amber-400 px-4 py-3 text-sm font-semibold text-neutral-950">{saving ? 'Adding…' : 'Add event'}</button></div></form></div></div></main>;
}

function Field({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="block text-sm text-neutral-300">{label}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2.5 text-white" /></label>; }
